process-engine/process_engine_contracts

- src/interfaces.ts
I added the Interfaces necessary for https://github.com/process-engine/process_engine/issues/9
This closes #3 
Related PRs: https://github.com/process-engine/process_engine/pull/10 and https://github.com/process-engine/process_engine_http/pull/2
When https://github.com/process-engine/process_engine/issues/9 is implemented, building the process_engine should not start throwing errors
> ✨  add getUserTask

- package.json
This branch contains fixes for bug that were introduced when namespacing and versioning were added.
Related PRs: see the branches `feature/namespace_versioning_fixes` on
- process_engine_meta
- core_contracts
- metadata_contracts
- metadata
- data_model_contracts
- process_engine_contracts
- core
- data_model
- datasource_adapter_postgres
- process_engine
- process_repository
- services
- skeleton
- consumer_client
- charon
Check out the meta-repo on branch `feature/namespace_versioning_fixes`, run the `setup.sh` and see if things still work.
> :anchor: bump version to 0.2.0

- src/interfaces.ts
This PR adds the interfaces necessary for the changes in https://github.com/process-engine/process_engine/pull/20
with this, you should be able to build the changes introduced in https://github.com/process-engine/process_engine/pull/20
> ✨ add interfaces for processdef-queries and processentity-creation

- src/entities/process/iprocess_def_entity.ts
This branch adds the "equals" method to compare two procesdefs with each other.
> ✨ Add equals

- src/iprocess_engine_service.ts
I added the contracts for a method that will allow us to directly import bpmn diagrams
You can't yet test them, but the process_engine_http and process_engine packages will soon use this method
> ✨ add createBpmnFromXml

- src/entities/process/iprocess_token_entity.ts
This adds a method to clone process tokens
You can now implement a method to clone process tokens without typescript nagging.
> ✨ add clone method to processtoken

- package.json
- src/iprocess_def_entity_type_service.ts
This adds a method to get a process definition by its name.
- Please have a look at this PR: https://github.com/process-engine/process_engine/pull/78
> :sparkles: Add getProcessDefinitionByName

- package.json
- src/iprocess_engine_service.ts
This PR fixes the parameters of the `createBpmnFromXml` function.
> 🐛 Fix Parameter Order Of createBpmnFromXml

- src/entities/process/iprocess_entity.ts
A few properties were missing in the `IProcessEntity` interface.
> Add isSubprocess and callerId to process entity interface

- src/new_model/runtime/index.ts
- src/new_model/runtime/messages/end_event_reached.ts
- src/new_model/runtime/messages/index.ts
I've added the `EndEventReachedMessage` to be able to notify when an EndEvent was reached.
It contains the `FlowNodeId` of the EndEvent reached, as well as the token payload.
See https://github.com/process-engine/process_engine_meta/pull/99.
> Add EndEventReached message

- src/runtime/storage/iflow_node_instance_repository.ts
- src/runtime/storage/iflow_node_instance_service.ts
* added `persistOnError` on `IFlowNodeInstanceRepository`
* added `persistOnError` on `IFlowNodeInstanceService`
See https://github.com/process-engine/process_engine_meta/pull/118.
> Add error persistance

- src/model/activities/tasks/user_task.ts
- src/model/types/form_field.ts
* make `preferedControl`-property optional
* https://github.com/process-engine/process_engine_meta/pull/120
* https://github.com/process-engine/consumer_api_meta/pull/38
> Implement prefered control

- PULL_REQUEST_TEMPLATE.md
- src/runtime/storage/iflow_node_instance_repository.ts
- src/runtime/storage/iflow_node_instance_service.ts
- src/runtime/types/flow_node_instance.ts
- src/runtime/types/flow_node_instance_state.ts
- src/runtime/types/index.ts
- src/runtime/types/process_token.ts
- src/runtime/types/process_token_type.ts
Part of the Heatmap feature.
- Remove `ExecutionContextFacade` parameter from the FlowNodeInstanceRepository interface
- Reorder the methods on that interface so that they are grouped together in a meaningful way
- Also change their signatures so that each state-changing method uses the same type of signature
- Suspend and Resume are no longer treated as a flag, but as an actual FlowNodeState
- FlowNodeInstances will no longer have only a single process token that gets updated every time its state changes
- The type of the token will be defined through the use of the enumeration `ProcessTokenType`
- Instead, each state change will produce its own process token. This will enable the heatmap to display token values for each stage of the FlowNodeInstances lifecycle
- Use string-values, …
> ♻️ Feature/store enter and exit token separately

- package.json
- src/runtime/storage/icorrelation_repository.ts
- src/runtime/storage/icorrelation_service.ts
- src/runtime/storage/index.ts
- src/runtime/storage/iprocess_definition_repository.ts
- src/runtime/storage/iprocess_model_service.ts
- src/runtime/types/correlation.ts
- src/runtime/types/correlation_from_repository.ts
- src/runtime/types/index.ts
- src/runtime/types/process_definition_from_repository.ts
- src/runtime/types/process_definition_raw.ts
**Changes:**
1. Add interface `ICorrelationRepository`. Currently supports:
- `createEntry` - Create a new netry in the database
- `getByCorrelationId` - Retrieve an entry by the given correlation id
2. Add type `CorrelationFromRepository`, which describes a correlation as it is retrieved from the repository
3. Add properties to `Correlation` runtime type:
- `processModelHash` - The process models hash
- `processModelXml` - The process models raw xml
- `createdAt` - The time at which the entry was created (i.e. the process model was run)
4. Changes to `ICorrelationService`:
- Remove `executionContextFacade`
- Add methods that correspond to those in the repository
5. Rename `ProcessDefinitionRaw` to `ProcessDefinitionFromRepository` and move it to the `Runtime.Types` namespace
6. Add …
> ✨ Get process definitions by correlation

- README.md
**Changes:**
Add a README.md file.
**Issues:**
Closes #29 
PR: #65
Read it.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: #NumberOfThisPR
</code>
</pre>
</details>
<details>
<summary>
Expand for a list of most used Emojis.
</summary>
<br>
Please prefix your …
>  📖 Add readme

- package.json
- src/runtime/storage/iflow_node_instance_repository.ts
- src/runtime/storage/iflow_node_instance_service.ts
**Changes:**
1. Use fixed dependency versions. The versions equal those that are most commonly used across the backend
2. Add `querySpecificFlowNode` function to the FlowNodeInstance persistence layer, which allows to retrieve a specific FlowNodeInstance by its correlationId, processModelId and flowNodeId (required for the heatmap)
3. Change return type of queryByFlowNodeId into an Array, since FlowNodeIds are not necessarily unique in this context
PR: #66
Implement the contracts somewhere.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code> …
> ✨ Add query for specific flow node

- src/model/activities/tasks/service_task.ts
**Changes:**
1. :sparkles: payload field added to ServiceTask model
PR: #73 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:** …
> :sparkles: add payload for external task

- package.json
- src/model/bpmn_component_tags.ts
- src/model/event_definitions/error_event_definition.ts
- src/model/event_definitions/message_event_definition.ts
- src/model/event_definitions/signal_event_definition.ts
- src/model/type_references/error_reference.ts
- src/model/type_references/index.ts
- src/model/type_references/message_reference.ts
**Changes:**
1. Remove all unused and unnecessary `type_references`. This includes:
- MessageReference
- ErrorReference
2. Add properties `name` and `id` to Event definitions
PR: #74
Implement the Contracts.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: …
> ♻️ Use name of signals and messages

- package.json
- src/runtime/storage/iflow_node_instance_repository.ts
- src/runtime/storage/iflow_node_instance_service.ts
- src/runtime/types/flow_node_instance.ts
**Changes:**
1. Adjust the parameter of the persist methods to user the complete "FlowNode" instead of onyl the id.
**Issues:**
Relates to: https://github.com/process-engine/process_engine_runtime/issues/133
PR: #77
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre> …
> ✨Adjust Parameters of Persist Methods

- package.json
- src/model/gateways/gateway.ts
**Changes:**
1. Use `Unspecified` as the default gateway type to make the handler more restrictive
2. Make the criteria for `Join` and `Split` more restrictive:
* Split Gateways must have only one incoming SequenceFlow, but can have multiple outgoing SFs
* Join Gateways must have only one outgoing SequenceFlow, but can have multiple incoming SFs
3. Use `Mixed` when incoming *and* outgoing SFs number more than one.
**Issues:**
Relates to https://github.com/process-engine/process_engine_runtime/issues/132
PR: #78
Implement the Contracts.
<details>
<summary>
</summary>
<br>
Please use `:twisted_rightwards_arrows:` at the beginning of your merge commit …
> 🔒🐛 Improve gateway handling

- package.json
- src/runtime/messages/event_aggregator_settings.ts
**Changes:**
Use Instance IDs for UserTask Events, instead of ModelIds.
This ensures that only one UserTask can ever be finished by a single request.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/126
PR: #75
Implement the Contracts and use the defined routes to handle UserTasks.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- …
> ♻️🔒 Use unique ids for UserTask events

- package.json
- src/constants.ts
- src/model/events/boundary_event.ts
- src/model/events/end_event.ts
- src/model/events/intermediate_catch_event.ts
- src/model/events/intermediate_throw_event.ts
- src/model/events/start_event.ts
- src/runtime/storage/iflow_node_instance_service.ts
- src/runtime/types/flow_node_instance.ts
**Changes:**
1. The the `eventType` to the different events.
**Issues:**
Relates to: https://github.com/process-engine/process_engine_runtime/issues/112
PR: #PullRequest
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes …
> ✨Add Event Types to Events

- src/runtime/storage/icorrelation_repository.ts
- src/runtime/storage/icorrelation_service.ts
- src/runtime/storage/idelete_process_model_service.ts
- src/runtime/storage/iflow_node_instance_repository.ts
- src/runtime/storage/iflow_node_instance_service.ts
- src/runtime/storage/index.ts
- src/runtime/storage/iprocess_definition_repository.ts
- src/runtime/storage/iprocess_model_service.ts
**Changes:**
1. Add delete process model functionality
**Issues:**
Related to https://github.com/process-engine/process_engine_runtime/issues/64
PR: #82
- **Have a look at https://github.com/process-engine/process_engine_runtime/pull/141**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
> ✨ Add Delete Process Model Functionality

- package.json
- src/runtime/storage/icorrelation_repository.ts
- src/runtime/storage/icorrelation_service.ts
- src/runtime/storage/iflow_node_instance_repository.ts
- src/runtime/storage/iflow_node_instance_service.ts
- src/runtime/types/correlation_from_repository.ts
- src/runtime/types/correlation_process_model.ts
**Changes:**
1. Add `parentProcessInstanceId` to Correlation type and all Correlation-related interfaces.
2. Add `getSubprocessesForProcessInstance` query to Correlation-related interfaces.
3. Add more UseCase specific queries to the `FlowNodeInstance` persistence interfaces.
PR: #86
Implement the Contracts.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes …
> ✨ Add UseCase specific queries to persistence layer

- package.json
- src/runtime/messages/event_aggregator_settings.ts
- src/runtime/messages/system_events/base_system_event_message.ts
- src/runtime/messages/system_events/index.ts
- src/runtime/messages/system_events/process_started.ts
---
**Changes:**
1. Send a notification which is send, when a new ProcessInstance starts.
**Issues:**
Related: https://github.com/process-engine/process_engine_runtime/issues/134
PR: #84
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code> …
> ✨ Implement ProcessStarted Notification

- src/runtime/storage/iflow_node_instance_repository.ts
- src/runtime/storage/iflow_node_instance_service.ts
**Changes:**
1. Add Queries For Correlation And ProcessModel
PR: #26
- **Have a look at https://github.com/process-engine/bpmn-studio/pull/1152**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: #NumberOfThisPR
</code>
</pre>
</details>
<details>
<summary>
Expand …
> ✨ Add Queries For Correlation And ProcessModel

- package.json
- src/runtime/engine/itimer_facade.ts
**Changes:**
Make the functions on the `ITimerFacade` run synchronously.
This is possible now, because all usages of the Timer repository have been removed from the TimerService, making the service synchronous as well.
PR: #89
Use the updated facade.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ... …
> 🔥 Remove timer repository

- package.json
- src/runtime/engine/itimer_facade.ts
**Changes:**
1. Upgrade `@essential-projects/event_aggregator_contracts` in order to use the new, refactored structure.
2. Add `cancelTimerSubscription` to the TimerFacade in order to be able to cancel timers, when a FlowNode was interrupted.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/184
PR: #91
Implement the Contracts.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, just copy the first part of this pull …
> ♻️ Refactor event aggregator

- package.json
- src/constants.ts
- src/model/bpmn_component_tags.ts
- src/model/event_definitions/index.ts
- src/model/event_definitions/link_event_definition.ts
- src/model/events/intermediate_catch_event.ts
- src/model/events/intermediate_throw_event.ts
- src/runtime/engine/iprocess_model_facade.ts
**Changes:**
1. Add tags, EventDefinitions and properties for supporting [IntermediateLinkEvents](https://docs.camunda.org/manual/7.7/reference/bpmn20/events/link-events/)
2. Add the `getLinkCatchEventByLinkName` function to the `ProcessModelFacade`, which will retrieve the `IntermediateLinkCatchEvent` for a given link name.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/163
PR: #92
Try modelling some intermediate link events and use the model parser to convert them into a usable object.
<details>
<summary>
</summary>
<br>
Example 1: …
> ✨ Implement link events

- src/runtime/storage/iflow_node_instance_repository.ts
- src/runtime/storage/iflow_node_instance_service.ts
> Related to https://github.com/process-engine/process_engine_runtime/pull/194
**Changes:**
1. Add query by ProcessInstanceId Functions
2. Fix Comment
PR: #93
-  **Have a look at https://github.com/process-engine/bpmn-studio/pull/1225**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
> ✨ Add Get Token by Process Instance Functionality

- src/model/activities/tasks/user_task.ts
**Changes:**
1. :sparkles: description and finishedMessage added
PR: #96 
Use the contracts to to manage UserTasks with the `description` and `finishedMessage` property.
> :sparkles: add description and finishedMessage for UserTasks

- src/runtime/storage/iflow_node_instance_repository.ts
- src/runtime/storage/iflow_node_instance_service.ts
- src/runtime/storage/iprocess_model_service.ts
> Related to https://github.com/process-engine/process_engine_runtime/pull/207
**Changes:**
1. Add getProcessModelByProcessInstanceId
PR: #97 
-  **Have a look at https://github.com/process-engine/bpmn-studio/pull/1225**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:** …
> ✨ Add getProcessModelByProcessInstanceId

- package.json
- src/runtime/storage/icorrelation_service.ts
**Changes:**
1. Add Users Identity to CorrelationService Methods
**Issues:**
Closes #https://github.com/process-engine/process_engine_runtime/issues/225
PR: #98 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong …
> ✨Add Identity to CorrelationService

- package.json
- src/runtime/messages/bpmn_events/error_end_event_reached.ts
- src/runtime/messages/bpmn_events/index.ts
- src/runtime/messages/bpmn_events/terminate_end_event_reached.ts
- src/runtime/messages/event_aggregator_settings.ts
- src/runtime/messages/system_events/index.ts
- src/runtime/messages/system_events/process_error.ts
- src/runtime/messages/system_events/process_terminated.ts
**Changes:**
1. Add message types for process errors and termination events
2. Use more comprehensive naming for the message paths to differentiate between global and instance-specific messages
PR: #113
Implement the new message types and refactor your use of the internal message paths
> ✨ CallActivity termination

- src/model_duplications/flow_nodes/end_event.ts
**Changes:**
Add optional `inputValues` property to the duplicated `EndEvent` model.
This allows a user to provide a customized payload with events that throw signals and messages.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/296
PR: #114
> ✨ Allow for customized event payloads

- src/model_duplications/flow_nodes/flow_node.ts
**Changes:**
Add `defaultOutgoingSequenceFlowId` property to duplicated FlowNode model.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/297
PR: #116
> ✨ Default Sequence Flows for ExclusiveGateways

- src/runtime/messages/event_aggregator_settings.ts
- src/runtime/messages/system_events/cronjob_base_system_event_message.ts
- src/runtime/messages/system_events/index.ts
1. Add cronjob messages
PR: #126 
> Describe how others can test your changes (not required when fixing typos, linter errors and such)
> ✨Add cronjob messages

- src/runtime/engine/facades/itimer_facade.ts
1. Fix Resuming Timer Events
Related to https://github.com/process-engine/process_engine_runtime/issues/549
PR: #129
- **Have a look at https://github.com/process-engine/process_engine_runtime/pull/554**
> 🐛 Fix Resuming Timer Events
